/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssd_assignment_3;

import cssd_assignment_3.Reports.FareEvasion;
import cssd_assignment_3.Reports.Report;
import cssd_assignment_3.Reports.ReportRegistry;
import java.awt.Desktop;
import java.awt.GridLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Ascendant
 */
public class AdminGUI extends javax.swing.JFrame {

    static EmployeeUserInterface EUI = null;
    Report currentOpenReport = null;
    /**
     * Creates new form AdminGUI
     * @param EUIp
     */
    public AdminGUI(EmployeeUserInterface EUIp) {
        initComponents();
        EUI = EUIp;
        listAccounts.setListData(EUI.getAccountList().toArray());
        if(!EUI.getActiveIsAdmin()) {
            tabsHomePage.setEnabledAt(1, false);
        }
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                EUI.saveAccounts();
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optAddUser = new javax.swing.JOptionPane();
        tabsHomePage = new javax.swing.JTabbedPane();
        pnlNews = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        pnlAccount = new javax.swing.JPanel();
        scrAccounts = new javax.swing.JScrollPane();
        listAccounts = new javax.swing.JList();
        lblCurrentAccounts = new javax.swing.JLabel();
        btnAddUser = new javax.swing.JButton();
        pnlReports = new javax.swing.JPanel();
        tabsReports = new javax.swing.JTabbedPane();
        pnlMaintenance = new javax.swing.JPanel();
        txtMainCosts = new javax.swing.JTextField();
        txtBreakCosts = new javax.swing.JTextField();
        txtExpensiveVehicles = new javax.swing.JTextField();
        txtCheapVehicles = new javax.swing.JTextField();
        btnPrintMaintenanceReport = new javax.swing.JButton();
        lblMaintenanceCosts = new javax.swing.JLabel();
        lblBreakdownCosts = new javax.swing.JLabel();
        lblMostExpensiveVehicles = new javax.swing.JLabel();
        lblCheapestVehicles = new javax.swing.JLabel();
        dpFromMaintenance = new org.jdesktop.swingx.JXDatePicker();
        lblFromMaintenance = new javax.swing.JLabel();
        lblToMaintenance = new javax.swing.JLabel();
        dpToMaintenance = new org.jdesktop.swingx.JXDatePicker();
        pnlCapacity = new javax.swing.JPanel();
        btnPrintCapacityReport = new javax.swing.JButton();
        lblOfTramsFull = new javax.swing.JLabel();
        txtTramsFull = new javax.swing.JTextField();
        txtTrainsFull = new javax.swing.JTextField();
        lblOfTrainsFull = new javax.swing.JLabel();
        lblOfBusesFull = new javax.swing.JLabel();
        txtBusesFull = new javax.swing.JTextField();
        lblToCapacity = new javax.swing.JLabel();
        dpToCapacity = new org.jdesktop.swingx.JXDatePicker();
        dpFromCapacity = new org.jdesktop.swingx.JXDatePicker();
        lblFromCapacity = new javax.swing.JLabel();
        pnlFinance = new javax.swing.JPanel();
        txtProfitLoss = new javax.swing.JTextField();
        lblProfitLoss = new javax.swing.JLabel();
        btnPrintFinanceReport = new javax.swing.JButton();
        dpFromFinance = new org.jdesktop.swingx.JXDatePicker();
        lblFromFinance = new javax.swing.JLabel();
        lblToFinance = new javax.swing.JLabel();
        dpToFinance = new org.jdesktop.swingx.JXDatePicker();
        pnlIncidents = new javax.swing.JPanel();
        btnPrintIncidentsReport = new javax.swing.JButton();
        lblUnsociableReports = new javax.swing.JLabel();
        txtUnsociableReports = new javax.swing.JTextField();
        lblIncidentReports = new javax.swing.JLabel();
        txtIncidentReports = new javax.swing.JTextField();
        lblDriversAccidentReports = new javax.swing.JLabel();
        txtDriversAccidentReports = new javax.swing.JTextField();
        btnGetDriversReport = new javax.swing.JButton();
        dpFromIncidents = new org.jdesktop.swingx.JXDatePicker();
        lblFromIncidents = new javax.swing.JLabel();
        lblToIncidents = new javax.swing.JLabel();
        dpToIncidents = new org.jdesktop.swingx.JXDatePicker();
        pnlFareEvasion = new javax.swing.JPanel();
        txtNumberOfEvadersCaught = new javax.swing.JTextField();
        txtRevenueRecovered = new javax.swing.JTextField();
        txtRevenueLost = new javax.swing.JTextField();
        lblRevenueLost = new javax.swing.JLabel();
        lblRevenueRecovered = new javax.swing.JLabel();
        lblNumEvadeCaught = new javax.swing.JLabel();
        btnPrintFareEvasionReport = new javax.swing.JButton();
        dpFromFareEvasion = new org.jdesktop.swingx.JXDatePicker();
        lblFromFareEvasion = new javax.swing.JLabel();
        lblToFareEvasion = new javax.swing.JLabel();
        dpToFareEvasion = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabsHomePage.setName(""); // NOI18N

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNewsLayout = new javax.swing.GroupLayout(pnlNews);
        pnlNews.setLayout(pnlNewsLayout);
        pnlNewsLayout.setHorizontalGroup(
            pnlNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNewsLayout.createSequentialGroup()
                .addContainerGap(351, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        pnlNewsLayout.setVerticalGroup(
            pnlNewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNewsLayout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        tabsHomePage.addTab("News", pnlNews);

        listAccounts.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrAccounts.setViewportView(listAccounts);

        lblCurrentAccounts.setText("Accounts");

        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAccountLayout = new javax.swing.GroupLayout(pnlAccount);
        pnlAccount.setLayout(pnlAccountLayout);
        pnlAccountLayout.setHorizontalGroup(
            pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountLayout.createSequentialGroup()
                .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAccountLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddUser))
                    .addGroup(pnlAccountLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblCurrentAccounts)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        pnlAccountLayout.setVerticalGroup(
            pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccountLayout.createSequentialGroup()
                .addGroup(pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAccountLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddUser))
                    .addGroup(pnlAccountLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblCurrentAccounts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabsHomePage.addTab("Accounts", pnlAccount);

        txtMainCosts.setEditable(false);
        txtMainCosts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMainCosts.setText("£");

        txtBreakCosts.setEditable(false);
        txtBreakCosts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBreakCosts.setText("£");

        txtExpensiveVehicles.setEditable(false);
        txtExpensiveVehicles.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtExpensiveVehicles.setText("????????");

        txtCheapVehicles.setEditable(false);
        txtCheapVehicles.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCheapVehicles.setText("????????");

        btnPrintMaintenanceReport.setText("PRINT REPORT");

        lblMaintenanceCosts.setText("Maintenance Costs");

        lblBreakdownCosts.setText("Breakdown Costs");

        lblMostExpensiveVehicles.setText("Most Expensive Vehicles");

        lblCheapestVehicles.setText("Cheapest Vehicles");

        lblFromMaintenance.setText("From:");

        lblToMaintenance.setText("To:");

        javax.swing.GroupLayout pnlMaintenanceLayout = new javax.swing.GroupLayout(pnlMaintenance);
        pnlMaintenance.setLayout(pnlMaintenanceLayout);
        pnlMaintenanceLayout.setHorizontalGroup(
            pnlMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaintenanceLayout.createSequentialGroup()
                .addGroup(pnlMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMaintenanceLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnPrintMaintenanceReport, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMaintenanceLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(pnlMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMainCosts)
                            .addComponent(txtBreakCosts)
                            .addComponent(txtExpensiveVehicles)
                            .addComponent(txtCheapVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaintenanceCosts)
                            .addComponent(lblBreakdownCosts)
                            .addComponent(lblMostExpensiveVehicles)
                            .addComponent(lblCheapestVehicles)))
                    .addGroup(pnlMaintenanceLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblFromMaintenance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpFromMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblToMaintenance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpToMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnlMaintenanceLayout.setVerticalGroup(
            pnlMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaintenanceLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dpFromMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFromMaintenance)
                    .addComponent(dpToMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblToMaintenance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(pnlMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMainCosts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaintenanceCosts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBreakCosts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBreakdownCosts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExpensiveVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMostExpensiveVehicles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCheapVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCheapestVehicles))
                .addGap(29, 29, 29)
                .addComponent(btnPrintMaintenanceReport, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        tabsReports.addTab("Maintenance", pnlMaintenance);

        btnPrintCapacityReport.setText("PRINT REPORT");
        btnPrintCapacityReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintCapacityReportActionPerformed(evt);
            }
        });

        lblOfTramsFull.setText("of trams full");

        txtTramsFull.setEditable(false);
        txtTramsFull.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTramsFull.setText("%");

        txtTrainsFull.setEditable(false);
        txtTrainsFull.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTrainsFull.setText("%");

        lblOfTrainsFull.setText("of trains full");

        lblOfBusesFull.setText("of buses full");

        txtBusesFull.setEditable(false);
        txtBusesFull.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBusesFull.setText("%");

        lblToCapacity.setText("To:");

        lblFromCapacity.setText("From:");

        javax.swing.GroupLayout pnlCapacityLayout = new javax.swing.GroupLayout(pnlCapacity);
        pnlCapacity.setLayout(pnlCapacityLayout);
        pnlCapacityLayout.setHorizontalGroup(
            pnlCapacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCapacityLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCapacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBusesFull)
                    .addComponent(txtTrainsFull)
                    .addComponent(txtTramsFull, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlCapacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOfBusesFull)
                    .addComponent(lblOfTrainsFull)
                    .addComponent(lblOfTramsFull))
                .addGap(104, 104, 104))
            .addGroup(pnlCapacityLayout.createSequentialGroup()
                .addGroup(pnlCapacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCapacityLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnPrintCapacityReport, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCapacityLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblFromCapacity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpFromCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblToCapacity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpToCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlCapacityLayout.setVerticalGroup(
            pnlCapacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCapacityLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlCapacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dpFromCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFromCapacity)
                    .addComponent(dpToCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblToCapacity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(pnlCapacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusesFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOfBusesFull))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCapacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrainsFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOfTrainsFull))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCapacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTramsFull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOfTramsFull))
                .addGap(41, 41, 41)
                .addComponent(btnPrintCapacityReport, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        tabsReports.addTab("Capacity", pnlCapacity);

        txtProfitLoss.setEditable(false);
        txtProfitLoss.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProfitLoss.setText("£");

        lblProfitLoss.setText("Profit / Loss");

        btnPrintFinanceReport.setText("PRINT REPORT");

        lblFromFinance.setText("From:");

        lblToFinance.setText("To:");

        javax.swing.GroupLayout pnlFinanceLayout = new javax.swing.GroupLayout(pnlFinance);
        pnlFinance.setLayout(pnlFinanceLayout);
        pnlFinanceLayout.setHorizontalGroup(
            pnlFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinanceLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(txtProfitLoss)
                .addGap(18, 18, 18)
                .addComponent(lblProfitLoss)
                .addGap(107, 107, 107))
            .addGroup(pnlFinanceLayout.createSequentialGroup()
                .addGroup(pnlFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFinanceLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnPrintFinanceReport, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFinanceLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblFromFinance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpFromFinance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblToFinance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpToFinance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnlFinanceLayout.setVerticalGroup(
            pnlFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFinanceLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dpFromFinance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFromFinance)
                    .addComponent(dpToFinance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblToFinance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(pnlFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfitLoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfitLoss))
                .addGap(100, 100, 100)
                .addComponent(btnPrintFinanceReport, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        tabsReports.addTab("Finance", pnlFinance);

        btnPrintIncidentsReport.setText("PRINT REPORT");

        lblUnsociableReports.setText("Unsociable Reports");

        lblIncidentReports.setText("Incident Reports");

        lblDriversAccidentReports.setText("Drivers Accident Reports");

        btnGetDriversReport.setText("Get drivers report");

        lblFromIncidents.setText("From:");

        lblToIncidents.setText("To:");

        javax.swing.GroupLayout pnlIncidentsLayout = new javax.swing.GroupLayout(pnlIncidents);
        pnlIncidents.setLayout(pnlIncidentsLayout);
        pnlIncidentsLayout.setHorizontalGroup(
            pnlIncidentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIncidentsLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnPrintIncidentsReport, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlIncidentsLayout.createSequentialGroup()
                .addGroup(pnlIncidentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIncidentsLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(pnlIncidentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlIncidentsLayout.createSequentialGroup()
                                .addComponent(txtDriversAccidentReports)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGetDriversReport))
                            .addGroup(pnlIncidentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDriversAccidentReports)
                                .addComponent(lblUnsociableReports)
                                .addComponent(txtUnsociableReports, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblIncidentReports)
                                .addComponent(txtIncidentReports, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlIncidentsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblFromIncidents)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpFromIncidents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblToIncidents)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpToIncidents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlIncidentsLayout.setVerticalGroup(
            pnlIncidentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIncidentsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlIncidentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dpFromIncidents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFromIncidents)
                    .addComponent(dpToIncidents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblToIncidents))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblUnsociableReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnsociableReports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIncidentReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIncidentReports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDriversAccidentReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIncidentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDriversAccidentReports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetDriversReport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrintIncidentsReport, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        tabsReports.addTab("Incidents", pnlIncidents);

        txtNumberOfEvadersCaught.setEditable(false);
        txtNumberOfEvadersCaught.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumberOfEvadersCaught.setText("#");

        txtRevenueRecovered.setEditable(false);
        txtRevenueRecovered.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRevenueRecovered.setText("£");

        txtRevenueLost.setEditable(false);
        txtRevenueLost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRevenueLost.setText("£");

        lblRevenueLost.setText("Revenue Lost");

        lblRevenueRecovered.setText("Revenue Recovered");

        lblNumEvadeCaught.setText("Number Of Evaders Caught");

        btnPrintFareEvasionReport.setText("PRINT REPORT");
        btnPrintFareEvasionReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintFareEvasionReportActionPerformed(evt);
            }
        });

        dpFromFareEvasion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpFromFareEvasionActionPerformed(evt);
            }
        });

        lblFromFareEvasion.setText("From:");

        lblToFareEvasion.setText("To:");

        dpToFareEvasion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpToFareEvasionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFareEvasionLayout = new javax.swing.GroupLayout(pnlFareEvasion);
        pnlFareEvasion.setLayout(pnlFareEvasionLayout);
        pnlFareEvasionLayout.setHorizontalGroup(
            pnlFareEvasionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFareEvasionLayout.createSequentialGroup()
                .addGroup(pnlFareEvasionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFareEvasionLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnPrintFareEvasionReport, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFareEvasionLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(pnlFareEvasionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumberOfEvadersCaught)
                            .addComponent(txtRevenueRecovered)
                            .addComponent(txtRevenueLost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFareEvasionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumEvadeCaught)
                            .addComponent(lblRevenueRecovered)
                            .addComponent(lblRevenueLost))))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFareEvasionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFromFareEvasion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpFromFareEvasion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblToFareEvasion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpToFareEvasion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        pnlFareEvasionLayout.setVerticalGroup(
            pnlFareEvasionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFareEvasionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlFareEvasionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dpFromFareEvasion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFromFareEvasion)
                    .addComponent(dpToFareEvasion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblToFareEvasion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(pnlFareEvasionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumberOfEvadersCaught, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumEvadeCaught))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFareEvasionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRevenueRecovered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRevenueRecovered))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFareEvasionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRevenueLost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRevenueLost))
                .addGap(36, 36, 36)
                .addComponent(btnPrintFareEvasionReport, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        tabsReports.addTab("FareEvasion", pnlFareEvasion);

        javax.swing.GroupLayout pnlReportsLayout = new javax.swing.GroupLayout(pnlReports);
        pnlReports.setLayout(pnlReportsLayout);
        pnlReportsLayout.setHorizontalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsReports)
        );
        pnlReportsLayout.setVerticalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsReports)
        );

        tabsHomePage.addTab("Reports", pnlReports);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsHomePage)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsHomePage)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintCapacityReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintCapacityReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintCapacityReportActionPerformed

    private void btnPrintFareEvasionReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintFareEvasionReportActionPerformed
        // TODO add your handling code here:
        if(EUI.getActiveIsAdmin()){
            if(currentOpenReport.getType() == 2) {
                String fileName = "FareEvasionReport" + currentOpenReport.getName() + ".txt";
                PrintWriter writer = null;
                try {
                    writer = new PrintWriter(fileName, "UTF-8");
                } catch (FileNotFoundException | UnsupportedEncodingException ex) {
                    Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                FareEvasion r = (FareEvasion) currentOpenReport;
                writer.println(r.toString().replace("\n", "\r\n"));
                writer.close();
                File file = new File(fileName);
                if (Desktop.isDesktopSupported()) {
                    try {
                        Desktop.getDesktop().edit(file);
                    } catch (IOException ex) {
                        Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Sorry but you need to be an admin to print a report.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPrintFareEvasionReportActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        JTextField username = new JTextField();
        JPasswordField password = new JPasswordField();
        JTextField securityLevel = new JTextField();
        JPanel myPanel = new JPanel();
        myPanel.setLayout(new GridLayout(3,2));
        myPanel.add(new JLabel("Username:"));
        myPanel.add(username);
        myPanel.add(new JLabel("Password:"));
        myPanel.add(password);
        myPanel.add(new JLabel("Security Level:"));
        myPanel.add(securityLevel);
        
        
        int result = JOptionPane.showConfirmDialog(null, myPanel, 
               "Please Enter the User Details", JOptionPane.OK_CANCEL_OPTION);
        if(result != JOptionPane.OK_CANCEL_OPTION) {
            String pass = new String(password.getPassword());
            if(username.getText().equals(""))
                JOptionPane.showMessageDialog(null, "Please enter a username");
            else if(pass.equals(""))
                JOptionPane.showMessageDialog(null, "Please enter a password");
            else if(securityLevel.getText().equals(""))
                JOptionPane.showMessageDialog(null, "Please enter a security level");
            else {
                Employee newEmployee = new Employee(username.getText(), pass, Integer.parseInt(securityLevel.getText()));
                EUI.addUser(newEmployee);
                listAccounts.setListData(EUI.getAccountList().toArray());
                listAccounts.repaint();
            }
        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void dpFromFareEvasionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpFromFareEvasionActionPerformed
        // TODO add your handling code here:
        getFareEvasionReport();
    }//GEN-LAST:event_dpFromFareEvasionActionPerformed

    private void dpToFareEvasionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpToFareEvasionActionPerformed
        // TODO add your handling code here:
        getFareEvasionReport();
    }//GEN-LAST:event_dpToFareEvasionActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        if(EUI.logout()) {
            this.setVisible(false);
            new LoginForm().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Error logging out, please close this window instead", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed
    
    private void getFareEvasionReport(){
        if(dpFromFareEvasion.getDate() != null && dpToFareEvasion.getDate() != null){
            currentOpenReport = EUI.getReport(2, dpFromFareEvasion.getDate(), dpToFareEvasion.getDate());
            if(currentOpenReport != null){
                if(currentOpenReport.getType() == 2) {
                    FareEvasion r = (FareEvasion) currentOpenReport;
                    txtNumberOfEvadersCaught.setText(String.valueOf(r.getHMC()));
                    txtRevenueRecovered.setText("£" + String.valueOf(r.revenueRecovered()));
                    txtRevenueLost.setText("£" + String.valueOf(r.revenueLost()));
                }
            } 
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminGUI(null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnGetDriversReport;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPrintCapacityReport;
    private javax.swing.JButton btnPrintFareEvasionReport;
    private javax.swing.JButton btnPrintFinanceReport;
    private javax.swing.JButton btnPrintIncidentsReport;
    private javax.swing.JButton btnPrintMaintenanceReport;
    private org.jdesktop.swingx.JXDatePicker dpFromCapacity;
    private org.jdesktop.swingx.JXDatePicker dpFromFareEvasion;
    private org.jdesktop.swingx.JXDatePicker dpFromFinance;
    private org.jdesktop.swingx.JXDatePicker dpFromIncidents;
    private org.jdesktop.swingx.JXDatePicker dpFromMaintenance;
    private org.jdesktop.swingx.JXDatePicker dpToCapacity;
    private org.jdesktop.swingx.JXDatePicker dpToFareEvasion;
    private org.jdesktop.swingx.JXDatePicker dpToFinance;
    private org.jdesktop.swingx.JXDatePicker dpToIncidents;
    private org.jdesktop.swingx.JXDatePicker dpToMaintenance;
    private javax.swing.JLabel lblBreakdownCosts;
    private javax.swing.JLabel lblCheapestVehicles;
    private javax.swing.JLabel lblCurrentAccounts;
    private javax.swing.JLabel lblDriversAccidentReports;
    private javax.swing.JLabel lblFromCapacity;
    private javax.swing.JLabel lblFromFareEvasion;
    private javax.swing.JLabel lblFromFinance;
    private javax.swing.JLabel lblFromIncidents;
    private javax.swing.JLabel lblFromMaintenance;
    private javax.swing.JLabel lblIncidentReports;
    private javax.swing.JLabel lblMaintenanceCosts;
    private javax.swing.JLabel lblMostExpensiveVehicles;
    private javax.swing.JLabel lblNumEvadeCaught;
    private javax.swing.JLabel lblOfBusesFull;
    private javax.swing.JLabel lblOfTrainsFull;
    private javax.swing.JLabel lblOfTramsFull;
    private javax.swing.JLabel lblProfitLoss;
    private javax.swing.JLabel lblRevenueLost;
    private javax.swing.JLabel lblRevenueRecovered;
    private javax.swing.JLabel lblToCapacity;
    private javax.swing.JLabel lblToFareEvasion;
    private javax.swing.JLabel lblToFinance;
    private javax.swing.JLabel lblToIncidents;
    private javax.swing.JLabel lblToMaintenance;
    private javax.swing.JLabel lblUnsociableReports;
    private javax.swing.JList listAccounts;
    private javax.swing.JOptionPane optAddUser;
    private javax.swing.JPanel pnlAccount;
    private javax.swing.JPanel pnlCapacity;
    private javax.swing.JPanel pnlFareEvasion;
    private javax.swing.JPanel pnlFinance;
    private javax.swing.JPanel pnlIncidents;
    private javax.swing.JPanel pnlMaintenance;
    private javax.swing.JPanel pnlNews;
    private javax.swing.JPanel pnlReports;
    private javax.swing.JScrollPane scrAccounts;
    private javax.swing.JTabbedPane tabsHomePage;
    private javax.swing.JTabbedPane tabsReports;
    private javax.swing.JTextField txtBreakCosts;
    private javax.swing.JTextField txtBusesFull;
    private javax.swing.JTextField txtCheapVehicles;
    private javax.swing.JTextField txtDriversAccidentReports;
    private javax.swing.JTextField txtExpensiveVehicles;
    private javax.swing.JTextField txtIncidentReports;
    private javax.swing.JTextField txtMainCosts;
    private javax.swing.JTextField txtNumberOfEvadersCaught;
    private javax.swing.JTextField txtProfitLoss;
    private javax.swing.JTextField txtRevenueLost;
    private javax.swing.JTextField txtRevenueRecovered;
    private javax.swing.JTextField txtTrainsFull;
    private javax.swing.JTextField txtTramsFull;
    private javax.swing.JTextField txtUnsociableReports;
    // End of variables declaration//GEN-END:variables
}
