/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssd_assignment_3;

import java.awt.CardLayout;

/**
 *
 * @author cHackz18
 */
public class Terminal extends javax.swing.JFrame {

    private int creditCardPaymentAmount = 0;
    
    /**
     * Creates new form Terminal
     */
    public Terminal() {
        initComponents();
        barcodeInvalidText.setVisible(false);
        MagneticStipInvalidText.setVisible(false);
        RFIDInvalidText.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DepositValueGroup = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        StartPanel = new javax.swing.JPanel();
        TerminalIntroHeader_text = new javax.swing.JLabel();
        MagneticStripCard_Button = new javax.swing.JButton();
        ContactlessCard_Button = new javax.swing.JButton();
        BardcodeCard_Button = new javax.swing.JButton();
        BardCodeMethod = new javax.swing.JPanel();
        BardcodeBegin_Button = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        barcodeInvalidText = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        MagneticStripMethod = new javax.swing.JPanel();
        SwipeCardToBegin_Button = new javax.swing.JButton();
        MagneticStipInvalidText = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        RFIDMethod = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        RFIDInvalidText = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Account = new javax.swing.JPanel();
        AccountTabs = new javax.swing.JTabbedPane();
        HomeTab = new javax.swing.JPanel();
        HomeStartPanel = new javax.swing.JPanel();
        CreditsRemainingField = new javax.swing.JTextField();
        Exit_Button = new javax.swing.JButton();
        CreditsRemainingLabel = new javax.swing.JLabel();
        AddCredits_Button = new javax.swing.JButton();
        CardNumberTitle = new javax.swing.JLabel();
        AddCreditsPanel = new javax.swing.JPanel();
        CardNumberTitleAddCredits = new javax.swing.JLabel();
        AddCreditsPrompt2 = new javax.swing.JLabel();
        AddCreditPrompt1 = new javax.swing.JLabel();
        AddCreditsExit_Button = new javax.swing.JButton();
        AddCreditsCard_Button = new javax.swing.JButton();
        AddCreditsCash_Button = new javax.swing.JButton();
        AddCreditsConfrimationPanel = new javax.swing.JPanel();
        CardNumberTitleConfirmation = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ConfirmationExit_Button = new javax.swing.JButton();
        CardPaymentMethodPanel = new javax.swing.JPanel();
        CardPaymentAddFive = new javax.swing.JToggleButton();
        CardPaymentAddTen = new javax.swing.JToggleButton();
        CardPaymentAddFifteen = new javax.swing.JToggleButton();
        CardPaymentTitleCardNumber = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CardPaymentExit_Button = new javax.swing.JButton();
        CardPaymentNext_Button1 = new javax.swing.JButton();
        CardDetailsInputPanel = new javax.swing.JPanel();
        CardDetailsTitle = new javax.swing.JLabel();
        CardDetailsAmountPounds = new javax.swing.JLabel();
        CardDetailsCreditsAmount = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CardNameField = new javax.swing.JTextField();
        CardNumberField = new javax.swing.JTextField();
        CardSecuirtyCodeField = new javax.swing.JTextField();
        CardDetailsFinish_Button = new javax.swing.JButton();
        CardDetailsExit_Button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CashPaymentPanel = new javax.swing.JPanel();
        CashPaymentTitleCardNo = new javax.swing.JLabel();
        CashPaymentCreditPrompt = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CashInsertedField = new javax.swing.JLabel();
        CreditsGainedField = new javax.swing.JLabel();
        CashPaymentFinish_Button = new javax.swing.JButton();
        CashPaymentExit_Button = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        JourneyHistoryTab = new javax.swing.JPanel();
        JourneyHistoryTitleCardNo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JourneyHistoryList = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        JourneyHistroyExit_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new java.awt.CardLayout());

        TerminalIntroHeader_text.setText("WHICH TYPE OF CARD DO YOU HAVE");

        MagneticStripCard_Button.setText("MAGNETIC STRIP CARD");
        MagneticStripCard_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MagneticStripCard_ButtonActionPerformed(evt);
            }
        });

        ContactlessCard_Button.setText("CONTACTLESS CARD");
        ContactlessCard_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactlessCard_ButtonActionPerformed(evt);
            }
        });

        BardcodeCard_Button.setText("BARCODE CARD");
        BardcodeCard_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BardcodeCard_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartPanelLayout = new javax.swing.GroupLayout(StartPanel);
        StartPanel.setLayout(StartPanelLayout);
        StartPanelLayout.setHorizontalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartPanelLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MagneticStripCard_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TerminalIntroHeader_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ContactlessCard_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BardcodeCard_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90))
        );
        StartPanelLayout.setVerticalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(TerminalIntroHeader_text)
                .addGap(18, 18, 18)
                .addComponent(MagneticStripCard_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContactlessCard_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BardcodeCard_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        MainPanel.add(StartPanel, "TopupStart");

        BardcodeBegin_Button.setText("BEGIN");
        BardcodeBegin_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BardcodeBegin_ButtonActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("INPUT BARCODE TO BEGIN");

        barcodeInvalidText.setBackground(new java.awt.Color(255, 178, 195));
        barcodeInvalidText.setText("    INVALID BARCODE TRY AGAIN");
        barcodeInvalidText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        barcodeInvalidText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BardCodeMethodLayout = new javax.swing.GroupLayout(BardCodeMethod);
        BardCodeMethod.setLayout(BardCodeMethodLayout);
        BardCodeMethodLayout.setHorizontalGroup(
            BardCodeMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BardCodeMethodLayout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(BardCodeMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BardCodeMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BardcodeBegin_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
            .addGroup(BardCodeMethodLayout.createSequentialGroup()
                .addGroup(BardCodeMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BardCodeMethodLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(barcodeInvalidText, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BardCodeMethodLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BardCodeMethodLayout.setVerticalGroup(
            BardCodeMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BardCodeMethodLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barcodeInvalidText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(BardcodeBegin_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainPanel.add(BardCodeMethod, "BarcodeMethod");

        SwipeCardToBegin_Button.setText("SWIPE CARD TO BEGIN");

        MagneticStipInvalidText.setText("       ERROR INVALID CARD TRY AGAIN");
        MagneticStipInvalidText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MagneticStripMethodLayout = new javax.swing.GroupLayout(MagneticStripMethod);
        MagneticStripMethod.setLayout(MagneticStripMethodLayout);
        MagneticStripMethodLayout.setHorizontalGroup(
            MagneticStripMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MagneticStripMethodLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(MagneticStripMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MagneticStripMethodLayout.createSequentialGroup()
                        .addGroup(MagneticStripMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SwipeCardToBegin_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MagneticStipInvalidText, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MagneticStripMethodLayout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        MagneticStripMethodLayout.setVerticalGroup(
            MagneticStripMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MagneticStripMethodLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(MagneticStipInvalidText)
                .addGap(18, 18, 18)
                .addComponent(SwipeCardToBegin_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainPanel.add(MagneticStripMethod, "MagneticMethod");

        jButton1.setText("TAP CARD TO BEGIN");

        RFIDInvalidText.setText("     ERROR INVALID CARD TRY AGAIN");
        RFIDInvalidText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RFIDMethodLayout = new javax.swing.GroupLayout(RFIDMethod);
        RFIDMethod.setLayout(RFIDMethodLayout);
        RFIDMethodLayout.setHorizontalGroup(
            RFIDMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RFIDMethodLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(RFIDMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RFIDInvalidText, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                .addGap(87, 87, 87))
            .addGroup(RFIDMethodLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RFIDMethodLayout.setVerticalGroup(
            RFIDMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RFIDMethodLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(RFIDInvalidText)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        MainPanel.add(RFIDMethod, "RFIDMethod");

        HomeTab.setLayout(new java.awt.CardLayout());

        CreditsRemainingField.setText("#");

        Exit_Button.setText("Exit");
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });

        CreditsRemainingLabel.setText("Credits Remaining");

        AddCredits_Button.setText("Add Credits");
        AddCredits_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCredits_ButtonActionPerformed(evt);
            }
        });

        CardNumberTitle.setText("CARD #");

        javax.swing.GroupLayout HomeStartPanelLayout = new javax.swing.GroupLayout(HomeStartPanel);
        HomeStartPanel.setLayout(HomeStartPanelLayout);
        HomeStartPanelLayout.setHorizontalGroup(
            HomeStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeStartPanelLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(CreditsRemainingField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(CreditsRemainingLabel)
                .addGap(96, 96, 96))
            .addGroup(HomeStartPanelLayout.createSequentialGroup()
                .addGroup(HomeStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeStartPanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(HomeStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddCredits_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(Exit_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(HomeStartPanelLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(CardNumberTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeStartPanelLayout.setVerticalGroup(
            HomeStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeStartPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(CardNumberTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(HomeStartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreditsRemainingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreditsRemainingLabel))
                .addGap(36, 36, 36)
                .addComponent(AddCredits_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Exit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        HomeTab.add(HomeStartPanel, "HomeStart");

        CardNumberTitleAddCredits.setText("CARD #");

        AddCreditsPrompt2.setText("PAYMENT METHOD");

        AddCreditPrompt1.setText("PLEASE SELECT");

        AddCreditsExit_Button.setText("EXIT");
        AddCreditsExit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCreditsExit_ButtonActionPerformed(evt);
            }
        });

        AddCreditsCard_Button.setText("CARD");
        AddCreditsCard_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCreditsCard_ButtonActionPerformed(evt);
            }
        });

        AddCreditsCash_Button.setText("CASH");
        AddCreditsCash_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCreditsCash_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddCreditsPanelLayout = new javax.swing.GroupLayout(AddCreditsPanel);
        AddCreditsPanel.setLayout(AddCreditsPanelLayout);
        AddCreditsPanelLayout.setHorizontalGroup(
            AddCreditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCreditsPanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(AddCreditsExit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AddCreditsPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(AddCreditsCard_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(AddCreditsCash_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddCreditsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddCreditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddCreditsPanelLayout.createSequentialGroup()
                        .addGroup(AddCreditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CardNumberTitleAddCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddCreditsPrompt2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddCreditsPanelLayout.createSequentialGroup()
                        .addComponent(AddCreditPrompt1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );
        AddCreditsPanelLayout.setVerticalGroup(
            AddCreditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCreditsPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(CardNumberTitleAddCredits)
                .addGap(28, 28, 28)
                .addComponent(AddCreditPrompt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddCreditsPrompt2)
                .addGap(18, 18, 18)
                .addGroup(AddCreditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCreditsCard_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddCreditsCash_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddCreditsExit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        HomeTab.add(AddCreditsPanel, "AddCredits");

        CardNumberTitleConfirmation.setText("CARD #");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("YOUR CREDITS HAVE BEEN");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("APPLIED TO YOUR ACCOUNT");

        ConfirmationExit_Button.setText("EXIT");
        ConfirmationExit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmationExit_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddCreditsConfrimationPanelLayout = new javax.swing.GroupLayout(AddCreditsConfrimationPanel);
        AddCreditsConfrimationPanel.setLayout(AddCreditsConfrimationPanelLayout);
        AddCreditsConfrimationPanelLayout.setHorizontalGroup(
            AddCreditsConfrimationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddCreditsConfrimationPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ConfirmationExit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddCreditsConfrimationPanelLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(AddCreditsConfrimationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CardNumberTitleConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddCreditsConfrimationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddCreditsConfrimationPanelLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(19, 19, 19))
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );
        AddCreditsConfrimationPanelLayout.setVerticalGroup(
            AddCreditsConfrimationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCreditsConfrimationPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(CardNumberTitleConfirmation)
                .addGap(41, 41, 41)
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(ConfirmationExit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        HomeTab.add(AddCreditsConfrimationPanel, "CreditsConfirm");

        DepositValueGroup.add(CardPaymentAddFive);
        CardPaymentAddFive.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CardPaymentAddFive.setText("£5");
        CardPaymentAddFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardPaymentAddFiveActionPerformed(evt);
            }
        });

        DepositValueGroup.add(CardPaymentAddTen);
        CardPaymentAddTen.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CardPaymentAddTen.setText("£10");
        CardPaymentAddTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardPaymentAddTenActionPerformed(evt);
            }
        });

        DepositValueGroup.add(CardPaymentAddFifteen);
        CardPaymentAddFifteen.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CardPaymentAddFifteen.setText("£15");
        CardPaymentAddFifteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardPaymentAddFifteenActionPerformed(evt);
            }
        });

        CardPaymentTitleCardNumber.setText("Card #");

        jLabel5.setText("SELECT DEPOSIT VALUE");

        CardPaymentExit_Button.setText("Exit");

        CardPaymentNext_Button1.setText("NEXT");
        CardPaymentNext_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardPaymentNext_Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CardPaymentMethodPanelLayout = new javax.swing.GroupLayout(CardPaymentMethodPanel);
        CardPaymentMethodPanel.setLayout(CardPaymentMethodPanelLayout);
        CardPaymentMethodPanelLayout.setHorizontalGroup(
            CardPaymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardPaymentMethodPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(CardPaymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardPaymentMethodPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardPaymentMethodPanelLayout.createSequentialGroup()
                        .addComponent(CardPaymentTitleCardNumber)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardPaymentMethodPanelLayout.createSequentialGroup()
                        .addComponent(CardPaymentNext_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(CardPaymentExit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(CardPaymentMethodPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(CardPaymentAddFive, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(CardPaymentAddTen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CardPaymentAddFifteen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CardPaymentMethodPanelLayout.setVerticalGroup(
            CardPaymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardPaymentMethodPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(CardPaymentTitleCardNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(CardPaymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardPaymentAddFive, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardPaymentAddFifteen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardPaymentAddTen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(CardPaymentMethodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardPaymentNext_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardPaymentExit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        HomeTab.add(CardPaymentMethodPanel, "CreditsCardPay");

        CardDetailsTitle.setText("CARD #");

        CardDetailsAmountPounds.setText("£ Amount ");

        CardDetailsCreditsAmount.setText("Credits Amount");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Card Name");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Card Number");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Security Code");

        CardNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardNameFieldActionPerformed(evt);
            }
        });

        CardNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardNumberFieldActionPerformed(evt);
            }
        });

        CardSecuirtyCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardSecuirtyCodeFieldActionPerformed(evt);
            }
        });

        CardDetailsFinish_Button.setText("FINISH");
        CardDetailsFinish_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardDetailsFinish_ButtonActionPerformed(evt);
            }
        });

        CardDetailsExit_Button.setText("EXIT");

        jLabel8.setText("TRANSACTION FAILED");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout CardDetailsInputPanelLayout = new javax.swing.GroupLayout(CardDetailsInputPanel);
        CardDetailsInputPanel.setLayout(CardDetailsInputPanelLayout);
        CardDetailsInputPanelLayout.setHorizontalGroup(
            CardDetailsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardDetailsInputPanelLayout.createSequentialGroup()
                .addGroup(CardDetailsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardDetailsInputPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(CardDetailsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CardDetailsInputPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CardDetailsInputPanelLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CardSecuirtyCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CardDetailsInputPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(CardDetailsFinish_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CardDetailsExit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CardDetailsInputPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(CardDetailsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CardDetailsCreditsAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CardNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CardDetailsInputPanelLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(CardDetailsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CardDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))))
                    .addGroup(CardDetailsInputPanelLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(CardDetailsAmountPounds)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        CardDetailsInputPanelLayout.setVerticalGroup(
            CardDetailsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardDetailsInputPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(CardDetailsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CardDetailsAmountPounds)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CardDetailsCreditsAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addGroup(CardDetailsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CardNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardDetailsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(CardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardDetailsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(CardSecuirtyCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CardDetailsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CardDetailsExit_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(CardDetailsFinish_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        HomeTab.add(CardDetailsInputPanel, "CreditsCardDetails");

        CashPaymentTitleCardNo.setText("CARD #");

        CashPaymentCreditPrompt.setText("   £1 = 1 Credit");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Cash Inserted");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Credits Gained");

        CashInsertedField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CashInsertedField.setText("VALUE");

        CreditsGainedField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CreditsGainedField.setText("VALUE");

        CashPaymentFinish_Button.setText("FINISH");
        CashPaymentFinish_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashPaymentFinish_ButtonActionPerformed(evt);
            }
        });

        CashPaymentExit_Button.setText("EXIT");
        CashPaymentExit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashPaymentExit_ButtonActionPerformed(evt);
            }
        });

        jTextField2.setText("Cash Here");

        javax.swing.GroupLayout CashPaymentPanelLayout = new javax.swing.GroupLayout(CashPaymentPanel);
        CashPaymentPanel.setLayout(CashPaymentPanelLayout);
        CashPaymentPanelLayout.setHorizontalGroup(
            CashPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CashPaymentPanelLayout.createSequentialGroup()
                .addGroup(CashPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CashPaymentPanelLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(CashPaymentTitleCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CashPaymentPanelLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(CashPaymentCreditPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CashPaymentPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(CashPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CashPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CashPaymentPanelLayout.createSequentialGroup()
                                .addComponent(CashInsertedField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CreditsGainedField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CashPaymentPanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(CashPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CashPaymentExit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CashPaymentFinish_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        CashPaymentPanelLayout.setVerticalGroup(
            CashPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CashPaymentPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(CashPaymentTitleCardNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CashPaymentCreditPrompt)
                .addGap(30, 30, 30)
                .addGroup(CashPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(CashInsertedField)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(CashPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(CreditsGainedField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CashPaymentFinish_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CashPaymentExit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        HomeTab.add(CashPaymentPanel, "CreditsCashPay");

        AccountTabs.addTab("Home", HomeTab);

        JourneyHistoryTitleCardNo.setText("CARD #");

        JourneyHistoryList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JourneyHistoryList);

        jLabel10.setText("JOURNEY HISTORY");

        JourneyHistroyExit_Button.setText("EXIT");
        JourneyHistroyExit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JourneyHistroyExit_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JourneyHistoryTabLayout = new javax.swing.GroupLayout(JourneyHistoryTab);
        JourneyHistoryTab.setLayout(JourneyHistoryTabLayout);
        JourneyHistoryTabLayout.setHorizontalGroup(
            JourneyHistoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JourneyHistoryTabLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(JourneyHistoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JourneyHistoryTitleCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
            .addGroup(JourneyHistoryTabLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(JourneyHistroyExit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JourneyHistoryTabLayout.setVerticalGroup(
            JourneyHistoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JourneyHistoryTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JourneyHistoryTitleCardNo)
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JourneyHistroyExit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AccountTabs.addTab("Journey History", JourneyHistoryTab);

        javax.swing.GroupLayout AccountLayout = new javax.swing.GroupLayout(Account);
        Account.setLayout(AccountLayout);
        AccountLayout.setHorizontalGroup(
            AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountTabs)
        );
        AccountLayout.setVerticalGroup(
            AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountTabs)
        );

        MainPanel.add(Account, "AccountHome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void AddCredits_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCredits_ButtonActionPerformed
        CardLayout card = (CardLayout)HomeTab.getLayout();
        card.show(HomeTab, "AddCredits");
    }//GEN-LAST:event_AddCredits_ButtonActionPerformed

    private void AddCreditsExit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCreditsExit_ButtonActionPerformed
        CardLayout card = (CardLayout)HomeTab.getLayout();
        card.show(HomeTab, "HomeStart");
    }//GEN-LAST:event_AddCreditsExit_ButtonActionPerformed

    private void AddCreditsCard_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCreditsCard_ButtonActionPerformed
        CardLayout card = (CardLayout)HomeTab.getLayout();
        card.show(HomeTab, "CreditsCardPay");
    }//GEN-LAST:event_AddCreditsCard_ButtonActionPerformed

    private void AddCreditsCash_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCreditsCash_ButtonActionPerformed
        CardLayout card = (CardLayout)HomeTab.getLayout();
        card.show(HomeTab, "CreditsCashPay");
    }//GEN-LAST:event_AddCreditsCash_ButtonActionPerformed

    private void ConfirmationExit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmationExit_ButtonActionPerformed
        CardLayout card = (CardLayout)HomeTab.getLayout();
        card.show(HomeTab, "HomeStart");
    }//GEN-LAST:event_ConfirmationExit_ButtonActionPerformed

    private void CardNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardNameFieldActionPerformed

    private void CardNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardNumberFieldActionPerformed

    private void CardSecuirtyCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardSecuirtyCodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardSecuirtyCodeFieldActionPerformed

    private void JourneyHistroyExit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JourneyHistroyExit_ButtonActionPerformed
        CardLayout card = (CardLayout)HomeTab.getLayout();
        card.show(HomeTab, "HomeStart");
    }//GEN-LAST:event_JourneyHistroyExit_ButtonActionPerformed

    private void MagneticStripCard_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MagneticStripCard_ButtonActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "MagneticMethod");
    }//GEN-LAST:event_MagneticStripCard_ButtonActionPerformed

    private void ContactlessCard_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactlessCard_ButtonActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "RFIDMethod");
    }//GEN-LAST:event_ContactlessCard_ButtonActionPerformed

    private void BardcodeCard_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BardcodeCard_ButtonActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "BarcodeMethod");
    }//GEN-LAST:event_BardcodeCard_ButtonActionPerformed

    private void BardcodeBegin_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BardcodeBegin_ButtonActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "AccountHome");
    }//GEN-LAST:event_BardcodeBegin_ButtonActionPerformed

    private void CardPaymentAddTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardPaymentAddTenActionPerformed
        creditCardPaymentAmount = 10;
    }//GEN-LAST:event_CardPaymentAddTenActionPerformed

    private void CardPaymentAddFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardPaymentAddFiveActionPerformed
        creditCardPaymentAmount = 5;
    }//GEN-LAST:event_CardPaymentAddFiveActionPerformed

    private void CardPaymentAddFifteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardPaymentAddFifteenActionPerformed
        creditCardPaymentAmount = 15;
    }//GEN-LAST:event_CardPaymentAddFifteenActionPerformed

    private void CardPaymentNext_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardPaymentNext_Button1ActionPerformed
        CardLayout card = (CardLayout)HomeTab.getLayout();
        card.show(HomeTab, "CreditsCardDetails");
    }//GEN-LAST:event_CardPaymentNext_Button1ActionPerformed

    private void CardDetailsFinish_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardDetailsFinish_ButtonActionPerformed
        CardLayout card = (CardLayout)HomeTab.getLayout();
        card.show(HomeTab, "CreditsConfirm");    
    }//GEN-LAST:event_CardDetailsFinish_ButtonActionPerformed

    private void CashPaymentFinish_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashPaymentFinish_ButtonActionPerformed
        CardLayout card = (CardLayout)HomeTab.getLayout();
        card.show(HomeTab, "CreditsConfirm");    
    }//GEN-LAST:event_CashPaymentFinish_ButtonActionPerformed

    private void CashPaymentExit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashPaymentExit_ButtonActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "TopupStart");   
    }//GEN-LAST:event_CashPaymentExit_ButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "TopupStart");   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "TopupStart");   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "TopupStart");  
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Terminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Account;
    private javax.swing.JTabbedPane AccountTabs;
    private javax.swing.JLabel AddCreditPrompt1;
    private javax.swing.JButton AddCreditsCard_Button;
    private javax.swing.JButton AddCreditsCash_Button;
    private javax.swing.JPanel AddCreditsConfrimationPanel;
    private javax.swing.JButton AddCreditsExit_Button;
    private javax.swing.JPanel AddCreditsPanel;
    private javax.swing.JLabel AddCreditsPrompt2;
    private javax.swing.JButton AddCredits_Button;
    private javax.swing.JPanel BardCodeMethod;
    private javax.swing.JButton BardcodeBegin_Button;
    private javax.swing.JButton BardcodeCard_Button;
    private javax.swing.JLabel CardDetailsAmountPounds;
    private javax.swing.JLabel CardDetailsCreditsAmount;
    private javax.swing.JButton CardDetailsExit_Button;
    private javax.swing.JButton CardDetailsFinish_Button;
    private javax.swing.JPanel CardDetailsInputPanel;
    private javax.swing.JLabel CardDetailsTitle;
    private javax.swing.JTextField CardNameField;
    private javax.swing.JTextField CardNumberField;
    private javax.swing.JLabel CardNumberTitle;
    private javax.swing.JLabel CardNumberTitleAddCredits;
    private javax.swing.JLabel CardNumberTitleConfirmation;
    private javax.swing.JToggleButton CardPaymentAddFifteen;
    private javax.swing.JToggleButton CardPaymentAddFive;
    private javax.swing.JToggleButton CardPaymentAddTen;
    private javax.swing.JButton CardPaymentExit_Button;
    private javax.swing.JPanel CardPaymentMethodPanel;
    private javax.swing.JButton CardPaymentNext_Button1;
    private javax.swing.JLabel CardPaymentTitleCardNumber;
    private javax.swing.JTextField CardSecuirtyCodeField;
    private javax.swing.JLabel CashInsertedField;
    private javax.swing.JLabel CashPaymentCreditPrompt;
    private javax.swing.JButton CashPaymentExit_Button;
    private javax.swing.JButton CashPaymentFinish_Button;
    private javax.swing.JPanel CashPaymentPanel;
    private javax.swing.JLabel CashPaymentTitleCardNo;
    private javax.swing.JButton ConfirmationExit_Button;
    private javax.swing.JButton ContactlessCard_Button;
    private javax.swing.JLabel CreditsGainedField;
    private javax.swing.JTextField CreditsRemainingField;
    private javax.swing.JLabel CreditsRemainingLabel;
    private javax.swing.ButtonGroup DepositValueGroup;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JPanel HomeStartPanel;
    private javax.swing.JPanel HomeTab;
    private javax.swing.JList<String> JourneyHistoryList;
    private javax.swing.JPanel JourneyHistoryTab;
    private javax.swing.JLabel JourneyHistoryTitleCardNo;
    private javax.swing.JButton JourneyHistroyExit_Button;
    private javax.swing.JLabel MagneticStipInvalidText;
    private javax.swing.JButton MagneticStripCard_Button;
    private javax.swing.JPanel MagneticStripMethod;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel RFIDInvalidText;
    private javax.swing.JPanel RFIDMethod;
    private javax.swing.JPanel StartPanel;
    private javax.swing.JButton SwipeCardToBegin_Button;
    private javax.swing.JLabel TerminalIntroHeader_text;
    private javax.swing.JLabel barcodeInvalidText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
